import { describe, expect, it } from "vitest";
import { deriveBackupOperationsHealth, getBackupConfigurationState, parseBackupManifest } from "./backup";
describe("backup operations", () => {
  it("uses deterministic checked-in tooling state", () => expect(getBackupConfigurationState()).toEqual({ logicalToolingAvailable: true, recoveryDocumentationAvailable: true, policyConfigured: true }));
  it("parses safe manifest checksum metadata", () => expect(parseBackupManifest({ manifestVersion: 1, backupCreatedAt: "2026-08-19T10:00:00.000Z", sizeBytes: 42, checksumSha256: "a".repeat(64), pgDumpVersion: "pg_dump 17.4", verificationStatus: "VERIFIED", verificationMethod: "pg_restore --list" })).toMatchObject({ sizeBytes: 42, checksumSha256: "a".repeat(64) }));
  it("does not penalize optional disabled PITR", () => { const now = new Date("2026-08-19T12:00:00Z"); const managed = { status: "VERIFIED" as const, verifiedAt: now, managedStatus: "ACTIVE" as const }; const logical = { status: "VERIFIED" as const, verifiedAt: now, backupCreatedAt: now }; expect(deriveBackupOperationsHealth({ now, managed, logical, restore: null, runbookAvailable: true })).toBe("WARNING"); expect(deriveBackupOperationsHealth({ now, managed, logical, restore: { status: "VERIFIED", verifiedAt: now }, runbookAvailable: true })).toBe("HEALTHY"); });
  it("reports stale, failed and missing verification", () => { const now = new Date("2026-08-19T12:00:00Z"); const managed = { status: "VERIFIED" as const, verifiedAt: now, managedStatus: "ACTIVE" as const }; expect(deriveBackupOperationsHealth({ now, managed, logical: { status: "VERIFIED", verifiedAt: new Date("2026-08-01T00:00:00Z") }, restore: null, runbookAvailable: true })).toBe("WARNING"); expect(deriveBackupOperationsHealth({ now, managed, logical: { status: "FAILED", verifiedAt: now }, restore: null, runbookAvailable: true })).toBe("FAILED"); expect(deriveBackupOperationsHealth({ now, managed: null, logical: null, restore: null, runbookAvailable: true })).toBe("UNKNOWN"); });
  it("fails inactive managed protection without fallback and warns for a failed rehearsal", () => { const now = new Date("2026-08-19T12:00:00Z"); expect(deriveBackupOperationsHealth({ now, managed: { status: "VERIFIED", verifiedAt: now, managedStatus: "INACTIVE" }, logical: null, restore: null, runbookAvailable: true })).toBe("FAILED"); expect(deriveBackupOperationsHealth({ now, managed: { status: "VERIFIED", verifiedAt: now, managedStatus: "ACTIVE" }, logical: { status: "VERIFIED", verifiedAt: now }, restore: { status: "FAILED", verifiedAt: now }, runbookAvailable: true })).toBe("WARNING"); });
});
