import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { createSentryHealthCache, deriveSentryHealth, fetchSentryLiveHealth, SENTRY_HEALTH_POLICY } from "./sentry-provider";
const issue = { id: "123", title: "Failure for student@example.com", level: "error", status: "unresolved", count: "4", firstSeen: "2026-08-19T00:00:00.000Z", lastSeen: "2026-08-19T01:00:00.000Z", culprit: "/api/test", stats: { "24h": [[1, 4]] } };
function fetchSequence(...responses: Response[]) { const mock = vi.fn(); responses.forEach((response) => mock.mockResolvedValueOnce(response)); return mock as unknown as typeof fetch; }
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json" } });
describe("Sentry live health provider", () => {
  it("is UNKNOWN without the read token", async () => expect(fetchSentryLiveHealth({ token: "", organization: "org", project: "project" })).resolves.toMatchObject({ status: "UNKNOWN", providerState: "NOT_CONFIGURED" }));
  it("returns a safe successful whitelist", async () => { const result = await fetchSentryLiveHealth({ token: "read-token", organization: "leadbridges", project: "web", fetchImpl: fetchSequence(json([[1, 7]]), json([issue])) }); expect(result).toMatchObject({ status: "WARNING", providerState: "AVAILABLE", errorEvents24h: 7, unresolvedIssues: 1 }); expect(result.issues[0]).toEqual(expect.objectContaining({ id: "123", title: "Failure for [Filtered]", transaction: "/api/test", url: "https://leadbridges.sentry.io/issues/123/" })); expect(JSON.stringify(result)).not.toContain("student@example.com"); });
  it.each([[401, "UNAUTHORIZED"], [403, "UNAUTHORIZED"], [429, "RATE_LIMITED"], [500, "UNAVAILABLE"]] as const)("handles HTTP %s", async (status, state) => expect(fetchSentryLiveHealth({ token: "read-token", organization: "org", project: "project", fetchImpl: fetchSequence(json({}, status), json([])) })).resolves.toMatchObject({ status: "UNKNOWN", providerState: state }));
  it("handles malformed responses", async () => expect(fetchSentryLiveHealth({ token: "read-token", organization: "org", project: "project", fetchImpl: fetchSequence(json({ bad: true }), json([])) })).resolves.toMatchObject({ status: "UNKNOWN", failureKind: "malformed-response" }));
  it("handles timeout without throwing", async () => expect(fetchSentryLiveHealth({ token: "read-token", organization: "org", project: "project", fetchImpl: vi.fn().mockRejectedValue(new Error("timeout")) })).resolves.toMatchObject({ status: "UNKNOWN", failureKind: "timeout-or-network" }));
  it("caches provider reads until the TTL expires", async () => { let now = 0; const loader = vi.fn(async () => ({ status: "HEALTHY", providerState: "AVAILABLE", errorEvents24h: 0, criticalEvents24h: 0, unresolvedIssues: 0, lastErrorAt: null, issues: [] } as const)); const cached = createSentryHealthCache(loader, 100, () => now); await cached(); await cached(); expect(loader).toHaveBeenCalledTimes(1); now = 101; await cached(); expect(loader).toHaveBeenCalledTimes(2); });
  it("derives deterministic levels", () => { expect(deriveSentryHealth({ configured: true, available: true, errorEvents24h: 0, criticalEvents24h: 0, unresolvedIssues: 0 })).toBe("HEALTHY"); expect(deriveSentryHealth({ configured: true, available: true, errorEvents24h: 1, criticalEvents24h: 0, unresolvedIssues: 1 })).toBe("WARNING"); expect(deriveSentryHealth({ configured: true, available: true, errorEvents24h: 1, criticalEvents24h: 1, unresolvedIssues: 1 })).toBe("DEGRADED"); expect(deriveSentryHealth({ configured: true, available: true, errorEvents24h: SENTRY_HEALTH_POLICY.spikeThreshold, criticalEvents24h: 0, unresolvedIssues: 0 })).toBe("DEGRADED"); expect(deriveSentryHealth({ configured: true, available: false, errorEvents24h: 0, criticalEvents24h: 0, unresolvedIssues: 0 })).toBe("UNKNOWN"); });
});
