import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";

const mocks = vi.hoisted(() => ({ requireAdmin: vi.fn(), getSnapshot: vi.fn() }));
vi.mock("@/features/auth/server/auth", () => ({ requireAdmin: mocks.requireAdmin }));
vi.mock("@/features/system-health/server", () => ({ getSystemHealthSnapshot: mocks.getSnapshot }));
vi.mock("@/features/system-health/components/backup-verification-form", () => ({ BackupVerificationForm: () => <div>Backup Durumunu Doğrula</div> }));
import SystemHealthPage from "./page";

beforeEach(() => { vi.clearAllMocks(); mocks.requireAdmin.mockResolvedValue({ role: "ADMIN" }); mocks.getSnapshot.mockResolvedValue({ overallStatus: "DEGRADED", generatedAt: new Date(), application: { status: "HEALTHY", label: "Running" }, database: { status: "HEALTHY", checked: true }, academyIntegration: { status: "UNKNOWN", configured: false, latestRun: null }, academyCron: { status: "UNKNOWN", latestCron: null, lastSuccessfulCron: null, nextScheduledAt: new Date() }, sentry: { status: "UNKNOWN", configured: false, serverDsnConfigured: false, clientDsnConfigured: false, errorMonitoringEnabled: false, tracingEnabled: false, traceSampleRate: 0.1, defaultPiiEnabled: false, sourceMapsConfigured: false }, backup: { status: "DEGRADED", strategy: "SUPABASE_MANAGED_PLUS_LOGICAL", managedBackupStatus: "UNKNOWN", pitrConfigured: "UNKNOWN", manualVerificationRequired: true, policyConfigured: true, logicalToolingAvailable: true, lastVerifiedLogicalBackupAt: null, lastVerificationStatus: "UNKNOWN", recoveryDocumentationAvailable: true }, security: { status: "WARNING", headers: { contentSecurityPolicy: true, frameProtection: true, hstsInProduction: true, mimeSniffingProtection: true, referrerPolicy: true }, adminAuthorization: true, sentryDefaultPiiDisabled: true, academySecretConfigured: true, cronSecretConfigured: true, publicQr: { tokenHashed: true, cryptographicEntropy: true, transactionalReplayProtection: true, originGuard: true, turnstile: "CONFIGURED", distributedRateLimit: "CONFIGURED" }, dependencyAudit: { auditedAt: new Date(), tool: "npm audit", total: 7, critical: 0, high: 7, moderate: 0, low: 0, knownRequestPathExploitableHigh: 0, note: "test" } }, release: { environment: "test", shortSha: null }, recentProblemRuns: [] }); });
describe("system health authorization", () => {
  it("requires ADMIN before loading monitoring data", async () => { await SystemHealthPage({ searchParams: Promise.resolve({}) }); expect(mocks.requireAdmin.mock.invocationCallOrder[0]).toBeLessThan(mocks.getSnapshot.mock.invocationCallOrder[0]); });
  it("does not load monitoring data when authorization fails", async () => { mocks.requireAdmin.mockRejectedValue(new Error("forbidden")); await expect(SystemHealthPage({ searchParams: Promise.resolve({}) })).rejects.toThrow("forbidden"); expect(mocks.getSnapshot).not.toHaveBeenCalled(); });
  it("renders the operational backup tab without secrets", async () => { const element = await SystemHealthPage({ searchParams: Promise.resolve({ tab: "backup" }) }); const html = renderToStaticMarkup(element); expect(html).toContain("Yedekleme durumu"); expect(html).toContain("Backup Durumunu Doğrula"); expect(html).not.toContain("BACKUP_DATABASE_URL"); });
  it("renders security posture without credential values", async () => { const element = await SystemHealthPage({ searchParams: Promise.resolve({ tab: "security" }) }); const html = renderToStaticMarkup(element); expect(html).toContain("Dependency audit"); expect(html).toContain("Distributed Rate Limit"); expect(html).toContain("CONFIGURED"); expect(html).not.toContain("CRON_SECRET="); });
  it("renders the performance tab from measured safe metadata", async () => { mocks.getSnapshot.mockResolvedValue({ overallStatus: "WARNING", generatedAt: new Date(), sentry: { tracingEnabled: true, traceSampleRate: 0.05 }, performance: { status: "WARNING", database: { status: "HEALTHY", probeDurationMs: 12 }, snapshot: { status: "HEALTHY", generationDurationMs: 25 }, academySync: { status: "HEALTHY", latestDurationMs: 10_000, lastSuccessfulDurationMs: 10_000, sampleCount: 2, minMs: 8_000, averageMs: 9_000, maxMs: 10_000 }, indexPosture: { status: "WARNING", livePlanVerified: false, recommendationCount: 2 }, externalDatabaseMetrics: "UNKNOWN" } }); const element = await SystemHealthPage({ searchParams: Promise.resolve({ tab: "performance" }) }); const html = renderToStaticMarkup(element); expect(html).toContain("Database probe"); expect(html).toContain("Academy sync süre trendi"); expect(html).toContain("UNKNOWN"); expect(html).not.toMatch(/SECRET|TOKEN/); });
  it("renders Release as information without an UNKNOWN badge", async () => { const html = renderToStaticMarkup(await SystemHealthPage({ searchParams: Promise.resolve({ tab: "overview" }) })); const start = html.indexOf(">Release<"); const release = html.slice(start, start + 700); expect(release).toContain("Aktif"); expect(release).not.toContain("UNKNOWN"); });
});
