/* eslint-disable react/no-unescaped-entities */
import { Activity, AppWindow, Clock3, Database, ExternalLink, Gauge, LockKeyhole, RadioTower, ServerCog, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { DashboardPage, DashboardSection, SectionHeading } from "@/components/dashboard/dashboard-page";
import { PageHeader } from "@/components/dashboard/page-header";
import { DataEmptyState } from "@/components/shared/data-surface";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireAdmin } from "@/features/auth/server/auth";
import { HealthStatusBadge } from "@/features/system-health/components/health-status-badge";
import { BackupVerificationForm } from "@/features/system-health/components/backup-verification-form";
import { getSystemHealthSnapshot, type SystemHealthSnapshot } from "@/features/system-health/server";
import { cn } from "@/lib/utils";

type Tab = "overview" | "errors" | "integrations" | "backup" | "security" | "performance";
const tabs: Array<{ value: Tab; label: string }> = [{ value: "overview", label: "Genel Bakış" }, { value: "errors", label: "Hatalar" }, { value: "integrations", label: "Entegrasyonlar" }, { value: "backup", label: "Yedekleme" }, { value: "security", label: "Güvenlik" }, { value: "performance", label: "Performans" }];
const dateFormatter = new Intl.DateTimeFormat("tr-TR", { timeZone: "Europe/Istanbul", dateStyle: "medium", timeStyle: "short" });
const formatDate = { format(value: unknown) { const date = value instanceof Date ? value : typeof value === "string" || typeof value === "number" ? new Date(value) : null; return date && Number.isFinite(date.getTime()) ? dateFormatter.format(date) : "—"; } };

function RunSummary({ run }: { run: NonNullable<SystemHealthSnapshot["academyIntegration"]["latestRun"]> }) {
  return <div className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3 lg:grid-cols-6">{[["Aday", run.candidateCount], ["Eşleşen", run.matchedCount], ["Bulunamayan", run.notFoundCount], ["Belirsiz", run.ambiguousCount], ["Adjustments", run.commissionAdjustmentCount], ["Hatalar", run.errorCount]].map(([label, value]) => <div key={String(label)} className="bg-card p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-xl font-semibold tabular-nums">{value}</div></div>)}</div>;
}

function Overview({ health }: { health: SystemHealthSnapshot }) {
  const cards = [
    { title: "Uygulama", icon: AppWindow, status: health.application.status, value: health.application.label, description: "Bu server-side snapshot başarıyla üretildi." },
    { title: "Database", icon: Database, status: health.database.status, value: health.database.checked ? "Connection probe tamamlandı" : "Kontrol edilmedi", description: "Doğrudan SELECT 1 bağlantı kontrolü." },
    { title: "Academy entegrasyonu", icon: RadioTower, status: health.academyIntegration.status, value: health.academyIntegration.latestRun ? formatDate.format(health.academyIntegration.latestRun.startedAt) : "Henüz çalışma yok", description: health.academyIntegration.configured ? "Bağlantı konfigürasyonu mevcut." : "Bağlantı konfigürasyonu eksik." },
    { title: "Academy cron", icon: Clock3, status: health.academyCron.status, value: health.academyCron.latestCron ? formatDate.format(health.academyCron.latestCron.startedAt) : "CRON çalışması bulunamadı", description: `Sonraki plan: ${formatDate.format(health.academyCron.nextScheduledAt)}` },
    { title: "Sentry", icon: ShieldCheck, status: health.sentry.status, value: health.sentry.providerState === "AVAILABLE" ? `Monitoring aktif · ${health.sentry.errorEvents24h ?? 0} hata` : "Live monitoring doğrulanamadı", description: health.sentry.providerState === "AVAILABLE" ? `Açık issue: ${health.sentry.unresolvedIssues ?? 0} · Son event: ${health.sentry.lastErrorAt ? formatDate.format(health.sentry.lastErrorAt) : "—"}` : "Configuration ile canlı provider erişimi ayrı değerlendirilir." },
    { title: "Release", icon: ServerCog, informational: true, value: health.release.shortSha ?? "Commit bilgisi yok", description: `Aktif · Ortam: ${health.release.environment}` },
  ];
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(({ title, icon: Icon, status, informational, value, description }) => <Card key={title} className="gap-4 py-5"><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-sm"><Icon className="size-4 text-primary" />{title}</CardTitle><CardDescription className="mt-2 leading-5">{description}</CardDescription></div>{informational ? <Badge variant="success">Aktif</Badge> : status ? <HealthStatusBadge status={status} /> : null}</CardHeader><CardContent><p className="break-words font-semibold">{value}</p></CardContent></Card>)}</div>;
}

function Errors({ health }: { health: SystemHealthSnapshot }) {
  const metrics = [["Monitoring", health.sentry.providerState], ["Son 24 saat errors", health.sentry.errorEvents24h ?? "—"], ["Critical / Fatal", health.sentry.criticalEvents24h ?? "—"], ["Open issues", health.sentry.unresolvedIssues ?? "—"], ["Last error", health.sentry.lastErrorAt ? formatDate.format(health.sentry.lastErrorAt) : "—"], ["Environment", health.release.environment], ["Active release", health.release.shortSha ?? "—"]];
  return <div className="grid gap-6"><Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>Sentry Live Monitoring</CardTitle><CardDescription>Raw event ve stack trace alınmadan, read-only operasyon özeti.</CardDescription></div><HealthStatusBadge status={health.sentry.status} /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <div key={String(label)} className="rounded-lg border bg-muted/15 p-4"><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-2 break-words font-semibold">{value}</div></div>)}</CardContent></Card><Card className="gap-0 overflow-hidden py-0"><div className="border-b p-5 sm:p-6"><SectionHeading title="Son Sentry issue'ları" description="Detaylı stack trace ve debugging Sentry panelinde kalır." /></div>{health.sentry.issues.length ? <Table><TableHeader><TableRow><TableHead>Issue</TableHead><TableHead>Seviye</TableHead><TableHead>Durum</TableHead><TableHead>Count</TableHead><TableHead>Last seen</TableHead><TableHead /></TableRow></TableHeader><TableBody>{health.sentry.issues.map((issue) => <TableRow key={issue.id}><TableCell className="max-w-md"><div className="break-words font-medium">{issue.title}</div>{issue.transaction ? <div className="mt-1 break-all font-mono text-xs text-muted-foreground">{issue.transaction}</div> : null}</TableCell><TableCell><Badge variant={["fatal","critical"].includes(issue.level.toLowerCase()) ? "destructive" : "warning"}>{issue.level}</Badge></TableCell><TableCell>{issue.status}</TableCell><TableCell>{issue.count}</TableCell><TableCell>{formatDate.format(issue.lastSeen)}</TableCell><TableCell><Button asChild size="sm" variant="outline"><a href={issue.url} target="_blank" rel="noreferrer">Sentry'de Aç <ExternalLink /></a></Button></TableCell></TableRow>)}</TableBody></Table> : <DataEmptyState title="Gösterilecek açık issue yok" description={health.sentry.providerState === "AVAILABLE" ? "Sentry API sorgusu başarıyla tamamlandı." : "Live Sentry verisi doğrulanamadı; configuration durumunu kontrol edin."} />}</Card></div>;
}

function Integrations({ health }: { health: SystemHealthSnapshot }) {
  const run = health.academyIntegration.latestRun;
  return <Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>LeadBridges Academy</CardTitle><CardDescription className="mt-2">Teknik bağlantı durumu ve güvenli senkronizasyon özeti.</CardDescription></div><HealthStatusBadge status={health.academyIntegration.status} /></CardHeader><CardContent className="grid gap-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Connection config", health.academyIntegration.configured ? "Present" : "Incomplete"], ["Son sync", run ? formatDate.format(run.startedAt) : "Henüz yok"], ["Son status / source", run ? `${run.status} · ${run.source}` : "Bilinmiyor"], ["Son başarılı CRON", health.academyCron.lastSuccessfulCron ? formatDate.format(health.academyCron.lastSuccessfulCron.startedAt) : "Bulunamadı"], ["Sonraki CRON", formatDate.format(health.academyCron.nextScheduledAt)]].map(([label, value]) => <div key={String(label)} className="rounded-lg border bg-muted/15 p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 font-semibold">{value}</div></div>)}</div>{run ? <RunSummary run={run} /> : null}<div><Button asChild variant="outline"><Link href="/dashboard/commissions">Komisyonlara git <ExternalLink /></Link></Button></div></CardContent></Card>;
}

function Backup({ health }: { health: SystemHealthSnapshot }) {
  const backup = health.backup;
  const checksum = backup.logical?.checksumSha256 ? `${backup.logical.checksumSha256.slice(0, 12)}…` : "—";
  const items = [["Managed Backup", backup.managed?.managedStatus ?? "Doğrulanmadı"], ["Son managed backup", backup.managed?.backupCreatedAt ? formatDate.format(backup.managed.backupCreatedAt) : "—"], ["Logical Backup", backup.logical?.status ?? "Doğrulanmadı"], ["Son logical backup", backup.logical?.backupCreatedAt ? formatDate.format(backup.logical.backupCreatedAt) : "—"], ["Boyut", backup.logical?.sizeBytes ? `${Number(backup.logical.sizeBytes).toLocaleString("tr-TR")} byte` : "—"], ["Checksum", checksum], ["PITR", backup.managed?.pitrStatus === "ENABLED" ? "Etkin" : backup.managed?.pitrStatus === "DISABLED" ? "Devre dışı · opsiyonel ek koruma" : "Bilinmiyor"], ["Recovery Runbook", backup.recoveryDocumentationAvailable ? "Hazır" : "Eksik"], ["Restore Rehearsal", backup.restore?.status === "VERIFIED" ? "Doğrulandı" : backup.restore?.status === "FAILED" ? "Başarısız" : "Henüz yapılmadı"]];
  return <div className="grid gap-6"><Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>Yedekleme durumu</CardTitle><CardDescription>Dosya veya credential saklanmadan, doğrulama metadata'sı.</CardDescription></div><HealthStatusBadge status={backup.status} /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(([label, value]) => <div key={String(label)} className="min-w-0 rounded-lg border bg-muted/15 p-4"><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-2 break-words font-semibold leading-6">{value}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Backup Durumunu Doğrula</CardTitle><CardDescription>Supabase Dashboard doğrulamasını ve isteğe bağlı logical manifesti kaydedin. PITR opsiyonel ek korumadır.</CardDescription></CardHeader><CardContent><BackupVerificationForm /></CardContent></Card></div>;
}

function Security({ health }: { health: SystemHealthSnapshot }) {
  const security = health.security;
  const controls = [
    ["Security headers / CSP", security.headers.contentSecurityPolicy && security.headers.frameProtection ? "Configured" : "Incomplete"],
    ["Production HSTS", security.headers.hstsInProduction ? "Configured" : "Incomplete"],
    ["Admin authorization", security.adminAuthorization ? "Server-side enforced" : "Incomplete"],
    ["Sentry default PII", security.sentryDefaultPiiDisabled ? "Disabled" : "Enabled"],
    ["Academy secret", security.academySecretConfigured ? "Present" : "Missing"],
    ["Cron secret", security.cronSecretConfigured ? "Present" : "Missing"],
  ];
  return <div className="grid gap-6"><Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><LockKeyhole className="size-4 text-primary" />Güvenlik duruşu</CardTitle><CardDescription className="mt-2">Credential değerleri gösterilmeden, uygulanan kontrollerin güvenli configuration-state özeti.</CardDescription></div><HealthStatusBadge status={security.status} /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{controls.map(([label, value]) => <div key={label} className="rounded-lg border bg-muted/15 p-4"><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-2 font-semibold">{value}</div></div>)}</CardContent></Card><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Public QR koruması</CardTitle><CardDescription>Provider uptime probe edilmez; configuration ve uygulama kontrolleri ayrı gösterilir.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm">{[["Token storage", security.publicQr.tokenHashed ? "SHA-256 hash" : "Unsafe"], ["Token entropy", security.publicQr.cryptographicEntropy ? "Cryptographic" : "Insufficient"], ["Replay protection", security.publicQr.transactionalReplayProtection ? "Transactional" : "Incomplete"], ["Origin guard", security.publicQr.originGuard ? "ENFORCED" : "NOT CONFIGURED"], ["Distributed Rate Limit", security.publicQr.distributedRateLimit], ["Turnstile", security.publicQr.turnstile]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-4 border-b pb-3 last:border-0 last:pb-0"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Dependency audit</CardTitle><CardDescription>{security.dependencyAudit.tool} · {formatDate.format(security.dependencyAudit.auditedAt)}</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Critical", security.dependencyAudit.critical], ["High", security.dependencyAudit.high], ["Moderate", security.dependencyAudit.moderate], ["Low", security.dependencyAudit.low]].map(([label, value]) => <div key={String(label)} className="rounded-lg border bg-muted/15 p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-xl font-semibold tabular-nums">{value}</div></div>)}</div><p className="mt-4 text-sm leading-6 text-muted-foreground">{security.dependencyAudit.note} İstek yolunda doğrulanmış exploitable high: {security.dependencyAudit.knownRequestPathExploitableHigh}.</p></CardContent></Card></div></div>;
}

function Performance({ health }: { health: SystemHealthSnapshot }) {
  const value = health.performance;
  const duration = (milliseconds: number | null) => milliseconds === null ? "Bilinmiyor" : milliseconds < 1_000 ? `${milliseconds.toFixed(0)} ms` : `${(milliseconds / 1_000).toFixed(1)} sn`;
  const cards = [
    ["Database probe", duration(value.database.probeDurationMs), value.database.status],
    ["System Health snapshot", duration(value.snapshot.generationDurationMs), value.snapshot.status],
    ["Son Academy sync", duration(value.academySync.latestDurationMs), value.academySync.latestDurationMs === null ? "UNKNOWN" : value.academySync.status],
    ["Son başarılı Academy sync", duration(value.academySync.lastSuccessfulDurationMs), value.academySync.status],
  ] as const;
  return <div className="grid gap-6"><Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><Gauge className="size-4 text-primary" />Performans özeti</CardTitle><CardDescription className="mt-2">Bu snapshot sırasında ve mevcut operasyon kayıtlarından ölçülen server-side değerler.</CardDescription></div><HealthStatusBadge status={value.status} /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, metric, status]) => <div key={label} className="rounded-lg border bg-muted/15 p-4"><div className="flex items-start justify-between gap-2"><span className="text-xs font-medium text-muted-foreground">{label}</span><HealthStatusBadge status={status} /></div><div className="mt-3 text-xl font-semibold tabular-nums">{metric}</div></div>)}</CardContent></Card><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Academy sync süre trendi</CardTitle><CardDescription>Son {value.academySync.sampleCount} tamamlanmış başarılı run üzerinden güvenli türetim.</CardDescription></CardHeader><CardContent className="grid grid-cols-3 gap-3">{[["Minimum", value.academySync.minMs], ["Ortalama", value.academySync.averageMs], ["Maksimum", value.academySync.maxMs]].map(([label, metric]) => <div key={String(label)} className="rounded-lg border bg-muted/15 p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 font-semibold tabular-nums">{duration(metric as number | null)}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Index / query posture</CardTitle><CardDescription>Schema-query audit sonucu; canlı EXPLAIN veya Supabase CPU/RAM metriği değildir.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex items-center justify-between gap-4"><span className="text-muted-foreground">Canlı query planı</span><span className="font-medium">{value.indexPosture.livePlanVerified ? "Doğrulandı" : "Doğrulanmadı"}</span></div><div className="flex items-center justify-between gap-4"><span className="text-muted-foreground">Takip önerileri</span><span className="font-medium tabular-nums">{value.indexPosture.recommendationCount}</span></div><div className="flex items-center justify-between gap-4"><span className="text-muted-foreground">Supabase CPU / RAM</span><span className="font-medium">{value.externalDatabaseMetrics}</span></div><div className="flex items-center justify-between gap-4"><span className="text-muted-foreground">Sentry tracing</span><span className="font-medium">{health.sentry.tracingEnabled ? `%${health.sentry.traceSampleRate * 100}` : "Devre dışı"}</span></div></CardContent></Card></div><p className="text-xs leading-5 text-muted-foreground">Süreler request-local ölçümler ve AcademySyncRun timestamp’lerinden hesaplanır. External provider sağlığı probe edilmez.</p></div>;
}

export default async function SystemHealthPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin();
  const params = await searchParams;
  const raw = Array.isArray(params.tab) ? params.tab[0] : params.tab;
  const tab: Tab = tabs.some((item) => item.value === raw) ? raw as Tab : "overview";
  const health = await getSystemHealthSnapshot();
  return <DashboardPage><PageHeader icon={Activity} title="Sistem Sağlığı" description="Uygulama, monitoring, cron ve entegrasyonların doğrulanabilir teknik durumunu izleyin." eyebrow={<HealthStatusBadge status={health.overallStatus} />} /><DashboardSection><nav aria-label="Sistem sağlığı bölümleri" className="flex max-w-full gap-1 overflow-x-auto rounded-lg border bg-card p-1">{tabs.map((item) => <Link key={item.value} href={`/dashboard/system-health?tab=${item.value}`} aria-current={tab === item.value ? "page" : undefined} className={cn("min-h-10 shrink-0 rounded-md px-4 py-2 text-sm font-medium transition-colors", tab === item.value ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted hover:text-foreground")}>{item.label}</Link>)}</nav></DashboardSection><DashboardSection>{tab === "overview" ? <Overview health={health} /> : tab === "errors" ? <Errors health={health} /> : tab === "integrations" ? <Integrations health={health} /> : tab === "backup" ? <Backup health={health} /> : tab === "security" ? <Security health={health} /> : <Performance health={health} />}</DashboardSection><p className="mt-6 text-xs text-muted-foreground">Snapshot: {formatDate.format(health.generatedAt)} · Europe/Istanbul</p></DashboardPage>;
}
