import { QrCode, Search } from "lucide-react"; import Link from "next/link";
import { DashboardPage } from "@/components/dashboard/dashboard-page"; import { PageHeader } from "@/components/dashboard/page-header"; import { DataEmptyState, DataPagination, FilterToolbar } from "@/components/shared/data-surface";
import { Button } from "@/components/ui/button"; import { Card } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireAdmin } from "@/features/auth/server/auth"; import { requireSelectedEvent } from "@/features/events/server/event-context"; import { QrRegistrationMatchCell } from "@/features/student-matching/components/qr-registration-match-cell"; import { listQrRegistrations } from "@/features/student-matching/queries/list-qr-registrations";
type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> }; const first = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v; const date = new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" });
function href(page: number, filters: { firstName?: string; lastName?: string; school?: string }) { const q = new URLSearchParams(); Object.entries(filters).forEach(([k,v]) => { if(v) q.set(k,v); }); if(page>1)q.set("page",String(page)); return `/dashboard/qr-registrations${q.size?`?${q}`:""}`; }
export default async function QrRegistrationsPage({ searchParams }: Props) {
  const user = await requireAdmin(); const event = await requireSelectedEvent(); const p = await searchParams; const filters = { firstName:first(p.firstName), lastName:first(p.lastName), school:first(p.school), matchStatus:first(p.matchStatus), attendance:first(p.attendance), enrollment:first(p.enrollment), sort:first(p.sort), pageSize:Number(first(p.pageSize)) }; const result = await listQrRegistrations({ ...filters, eventId:event.id, page:Number(first(p.page)) });
  return <DashboardPage><PageHeader icon={QrCode} title="QR Kayıtları" description="QR üzerinden kayıt olan öğrencileri ve eşleşme durumlarını görüntüleyin."/><Card className="mt-6 gap-0 overflow-hidden py-0"><FilterToolbar className="md:grid-cols-[1fr_1fr_1.2fr_auto] md:items-end">{[["firstName","Ad"],["lastName","Soyad"],["school","Okul"]].map(([key,label])=><div key={key} className="grid gap-2"><Label htmlFor={`qr-${key}`}>{label}</Label><Input id={`qr-${key}`} name={key} defaultValue={filters[key as keyof typeof filters]} /></div>)}<div className="flex flex-wrap gap-2"><Button type="submit"><Search/>Ara</Button><Button asChild variant="outline"><Link href="/dashboard/qr-registrations">Temizle</Link></Button></div></FilterToolbar>{result.records.length?<Table><TableHeader><TableRow><TableHead>Ad Soyad</TableHead><TableHead>Okul</TableHead><TableHead>Telefon</TableHead><TableHead>QR Seri</TableHead><TableHead>Kayıt Tarihi</TableHead><TableHead>Eşleşme</TableHead></TableRow></TableHeader><TableBody>{result.records.map(r=><TableRow key={r.id}><TableCell>{r.firstName} {r.lastName}</TableCell><TableCell className="max-w-56 truncate">{r.school}</TableCell><TableCell>{r.phone}</TableCell><TableCell className="font-mono text-xs">{r.qrCode.serialNumber}</TableCell><TableCell>{date.format(r.registeredAt)}</TableCell><TableCell><QrRegistrationMatchCell role={user.role} registration={r}/></TableCell></TableRow>)}</TableBody></Table>:<DataEmptyState title={result.hasFilters?"Aramayla eşleşen QR kaydı bulunamadı":"Henüz QR kaydı yok"} description={result.hasFilters?"Filtreleri sadeleştirerek yeniden deneyin.":"Yeni QR formları gönderildiğinde kayıtlar burada görünecek."}/>}<DataPagination summary={`Toplam ${result.total} · Sayfa ${result.page}/${result.pageCount}`}><Button size="sm" variant="outline" asChild={result.page>1} disabled={result.page<=1}>{result.page>1?<Link href={href(result.page-1,filters)}>Önceki</Link>:<span>Önceki</span>}</Button><Button size="sm" variant="outline" asChild={result.page<result.pageCount} disabled={result.page>=result.pageCount}>{result.page<result.pageCount?<Link href={href(result.page+1,filters)}>Sonraki</Link>:<span>Sonraki</span>}</Button></DataPagination></Card></DashboardPage>;
}
