import Link from "next/link";
import { Activity, Clock3, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ManualSyncButton } from "@/features/academy-commissions/components/manual-sync-button";
import { commissionFilterHref, parseCommissionFilter, type CommissionFilter } from "@/features/academy-commissions/filters";
import { listAcademyCommissions } from "@/features/academy-commissions/list";
import { getAcademySyncMonitoring } from "@/features/academy-commissions/monitoring";
import { ACADEMY_SYNC_TIME_ZONE } from "@/features/academy-commissions/schedule";
import { requireAdmin } from "@/features/auth/server/auth";
const money = (value: number, currency = "TRY") => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(value);
const date = new Intl.DateTimeFormat("tr-TR", { timeZone: ACADEMY_SYNC_TIME_ZONE, dateStyle: "short", timeStyle: "short" });
const statusLabel = (status: string) => status === "COMPLETED" ? "SUCCESS" : status;
const statusVariant = (status: string) => status === "COMPLETED" ? "success" as const : status === "PARTIAL" || status === "RUNNING" ? "warning" as const : "destructive" as const;
const href = (page: number, search: string, filter: CommissionFilter, historyPage?: number) => { const q = new URLSearchParams({ filter }); if (search) q.set("search", search); if (page > 1) q.set("page", String(page)); if (historyPage && historyPage > 1) q.set("historyPage", String(historyPage)); return `?${q}`; };
export default async function CommissionsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const p = await searchParams; const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
  const search = first(p.search) ?? "", filter = parseCommissionFilter(first(p.filter)), page = Number(first(p.page)) || 1, historyPage = Number(first(p.historyPage)) || 1;
  const [result, monitoring] = await Promise.all([listAcademyCommissions(search, page, filter), getAcademySyncMonitoring(historyPage)]); const latest = monitoring.latest;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><h1 className="text-3xl font-semibold">Komisyonlar</h1><p className="mt-2 text-muted-foreground">Academy eşleşmelerini, ödeme farklarını ve değiştirilemez komisyon hareketlerini izleyin.</p>
    <Card className="mt-8 gap-5 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex items-center gap-2 font-semibold"><Activity className="size-4 text-emerald-600"/>Academy Senkronizasyonu</div><p className="mt-1 text-xs text-muted-foreground">Son otomatik ve manuel çalışmaların güvenli operasyon özeti</p></div><ManualSyncButton/></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Son senkronizasyon", latest ? date.format(latest.finishedAt ?? latest.startedAt) : "Henüz yok"],["Durum", latest ? statusLabel(latest.status) : "—"],["Kaynak", latest?.source ?? "—"],["Sonraki otomatik çalışma", date.format(monitoring.nextScheduledAt)]].map(([label,value]) => <div key={label} className="rounded-md border bg-muted/30 p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 font-medium">{value}</div></div>)}</div>
      <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6">{[["Aday",latest?.candidateCount],["Eşleşen",latest?.matchedCount],["Bulunamayan",latest?.notFoundCount],["Belirsiz",latest?.ambiguousCount],["Adjustments",latest?.commissionAdjustmentCount],["Hatalar",latest?.errorCount]].map(([label,value]) => <div key={label as string}><span className="text-muted-foreground">{label}</span><div className="text-lg font-semibold">{value ?? 0}</div></div>)}</div>
    </Card>
    <Card className="mt-6 gap-0 overflow-hidden py-0"><div className="flex flex-col gap-4 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex w-fit rounded-md border bg-muted/40 p-1" aria-label="Eşleşme filtresi">{([['matched','Eşleşenler'],['unmatched','Eşleşmeyenler']] as const).map(([value,label]) => <Button key={value} asChild size="sm" variant={filter === value ? "default" : "ghost"}><Link aria-current={filter === value ? "page" : undefined} href={commissionFilterHref(value, search)}>{label}</Link></Button>)}</div><form className="flex gap-2"><input type="hidden" name="filter" value={filter}/><Input name="search" defaultValue={search} placeholder="Öğrenci veya kayıt referansı"/><Button><Search/>Ara</Button></form></div>
      <Table><TableHeader><TableRow><TableHead>Öğrenci / Referans</TableHead><TableHead>Durum</TableHead><TableHead>Academy ödeme</TableHead><TableHead>Son fark</TableHead><TableHead>%25 komisyon</TableHead><TableHead>Toplam komisyon</TableHead><TableHead>Son sync</TableHead></TableRow></TableHeader><TableBody>{result.items.map((item) => { const latestLedger = item.vrRecord.academyLedger[0], snapshot = item.vrRecord.academySnapshot; return <TableRow key={item.id}><TableCell><div className="font-medium">{item.vrRecord.firstName} {item.vrRecord.lastName}</div><div className="font-mono text-xs text-muted-foreground">{item.qrRegistration.qrCode.serialNumber}</div>{item.vrRecord.academyLedger.length ? <details className="mt-2"><summary className="cursor-pointer text-xs">Ledger geçmişi ({item.vrRecord.academyLedger.length})</summary>{item.vrRecord.academyLedger.map((row) => <div key={row.id} className="mt-1 text-xs">{money(row.commissionAmount.toNumber(), row.currency)} | {money(row.academyPaymentDelta.toNumber(), row.currency)} ödeme farkı</div>)}</details> : null}</TableCell><TableCell><Badge variant={item.status === "MATCHED" ? "success" : item.status === "AMBIGUOUS" ? "warning" : "outline"}>{item.status}</Badge></TableCell><TableCell>{snapshot ? money(snapshot.lastObservedPaidAmount.toNumber(), snapshot.currency) : "—"}</TableCell><TableCell>{latestLedger ? money(latestLedger.academyPaymentDelta.toNumber(), latestLedger.currency) : "—"}</TableCell><TableCell>{latestLedger ? money(latestLedger.commissionAmount.toNumber(), latestLedger.currency) : "—"}</TableCell><TableCell>{money(item.totalCommission, snapshot?.currency ?? latestLedger?.currency ?? "TRY")}</TableCell><TableCell>{date.format(item.lastCheckedAt)}</TableCell></TableRow>})}</TableBody></Table>
      <div className="flex justify-between border-t p-5 text-sm"><span>Toplam {result.total}</span><div className="flex gap-2">{result.page > 1 ? <Button asChild variant="outline"><Link href={href(result.page - 1, search, filter, historyPage)}>Önceki</Link></Button> : null}{result.page < result.pageCount ? <Button asChild variant="outline"><Link href={href(result.page + 1, search, filter, historyPage)}>Sonraki</Link></Button> : null}</div></div></Card>
    <Card className="mt-6 gap-0 overflow-hidden py-0"><div className="flex items-center gap-2 border-b p-5 font-semibold"><Clock3 className="size-4"/>Senkronizasyon Geçmişi</div><Table><TableHeader><TableRow><TableHead>Tarih</TableHead><TableHead>Durum</TableHead><TableHead>Kaynak</TableHead><TableHead>Aday</TableHead><TableHead>Matched</TableHead><TableHead>Not Found</TableHead><TableHead>Ambiguous</TableHead><TableHead>Adjustments</TableHead><TableHead>Errors</TableHead><TableHead>Süre</TableHead></TableRow></TableHeader><TableBody>{monitoring.history.map((run) => <TableRow key={run.id}><TableCell>{date.format(run.startedAt)}</TableCell><TableCell><Badge variant={statusVariant(run.status)}>{statusLabel(run.status)}</Badge></TableCell><TableCell>{run.source}</TableCell><TableCell>{run.candidateCount}</TableCell><TableCell>{run.matchedCount}</TableCell><TableCell>{run.notFoundCount}</TableCell><TableCell>{run.ambiguousCount}</TableCell><TableCell>{run.commissionAdjustmentCount}</TableCell><TableCell>{run.errorCount}</TableCell><TableCell>{run.finishedAt ? `${Math.max(0, Math.round((run.finishedAt.getTime()-run.startedAt.getTime())/1000))} sn` : "Devam ediyor"}</TableCell></TableRow>)}</TableBody></Table><div className="flex justify-end gap-2 border-t p-5">{monitoring.page > 1 ? <Button asChild variant="outline" size="sm"><Link href={href(page, search, filter, monitoring.page-1)}>Önceki</Link></Button> : null}{monitoring.page < monitoring.pageCount ? <Button asChild variant="outline" size="sm"><Link href={href(page, search, filter, monitoring.page+1)}>Sonraki</Link></Button> : null}</div></Card>
  </main>;
}
