export const AUDIT_ACTIONS = {
  STUDENT_MATCH_REMOVED: "STUDENT_MATCH_REMOVED",
  QR_ASSIGNMENT_REVERSED: "QR_ASSIGNMENT_REVERSED",
  ATTENDANCE_MARKED: "ATTENDANCE_MARKED",
  ATTENDANCE_REVERSED: "ATTENDANCE_REVERSED",
  COURSE_ENROLLMENT_MARKED: "COURSE_ENROLLMENT_MARKED",
  COURSE_ENROLLMENT_REVERSED: "COURSE_ENROLLMENT_REVERSED",
  VR_RECORD_UPDATED: "VR_RECORD_UPDATED",
  VR_RECORD_ARCHIVED: "VR_RECORD_ARCHIVED",
  SCHOOL_DEACTIVATED: "SCHOOL_DEACTIVATED",
  SCHOOL_REACTIVATED: "SCHOOL_REACTIVATED",
  QR_CODE_ARCHIVED: "QR_CODE_ARCHIVED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
