export const NOTIFICATION_TYPES = {
  IMPORT_COMPLETED: "IMPORT_COMPLETED",
  IMPORT_FAILED: "IMPORT_FAILED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  CRITICAL_REVERSAL: "CRITICAL_REVERSAL",
  EVENT_STATUS_CHANGED: "EVENT_STATUS_CHANGED",
  SYSTEM_WARNING: "SYSTEM_WARNING",
} as const;
export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
